### ISSUE TITLE
Download Android code

### ISSUE THREAD

**Issue by fazioa** [souliss/souliss#103]
Original [issue 106](https://code.google.com/p/souliss/issues/detail?id=106) created by fazioa on 2015-02-01T15:39:47.000Z:

<b>What steps will reproduce the problem?</b>
1. I go to SoulissApp for Android
2. And I try it to download the &quot;Git Repository&quot;.
3. But when i'm trying to download, I get that I am an unauthorized user

<b>What is the expected output? What do you see instead?</b>
I want the code, please. I want to colaborate with the proyect.
This is my blog http://cursoandroidstudio.blogspot.com.ar/

ramiro madriaga
ramiro.madriaga@gmail.com

**Comment by plinioseniore** [comment]
This problem was in googlecode, now with github is no longer here.
