### ISSUE TITLE
Analog Lux value on SoulissApp

### ISSUE THREAD

**Issue by fazioa** [souliss/souliss#106]
Original [issue 109](https://code.google.com/p/souliss/issues/detail?id=109) created by fazioa on 2015-02-21T21:17:32.000Z:

<b>What steps will reproduce the problem?</b>
1. Define a T54 and read the value on SoulissApp

<b>What is the expected output? What do you see instead?</b>

The value on SoulissApp is 10k bigger than the one on Souliss, scaling shall be on node side and not on the app. Normal values in Lux are from 0 to 1000.

**Comment by juanpintom** [comment]
If you take a look to the "in, out" arrays on this example:
https://github.com/juanpintom/Souliss_ESP_Examples/blob/master/E03_ESP_LDR.ino

You can see I get the values in Lux/10 and after import the value to the slot I divide by 100 other time, so the value must be readed on kLux, I need some time to recalibrate the function to work with ESP, but I'll let you know when I've more reference values.

**Comment by plinioseniore** [comment]
The App should not scale the value, because is a floating point and can be used as is.

**Comment by plinioseniore** [comment]
https://github.com/souliss/soulissapp/issues/11
