### ISSUE TITLE
Broadcast Setting

### ISSUE THREAD

**Issue by fazioa** [souliss/souliss#107]
Original [issue 110](https://code.google.com/p/souliss/issues/detail?id=110) created by fazioa on 2015-02-21T23:12:11.000Z:

<b>What steps will reproduce the problem?</b>
1. In Network Options use Broadcast Settings

<b>What is the expected output? What do you see instead?</b>

SoulissApp should send a broadcast UDP/IP frame on port 230 with the IP information (address, subnetmask, gateway, SSID for WiFi and Password for WiFi).

Actually SoulissApp doesn't send any broadcast frame.

Please note also that all the IP setting are shown in the app in a reverse way, like 0.255.255.255. This is probably due to a bigendian way to handle word.

**Comment by plinioseniore** [comment]
Moved in soulissapp issue list
https://github.com/souliss/soulissapp/issues/1
