### ISSUE TITLE
AndroidAirConditioner, AndroidRGBLamp not proceed to detail

### ISSUE THREAD

**Issue by fazioa** [souliss/souliss#11]
Original [issue 11](https://code.google.com/p/souliss/issues/detail?id=11) created by fazioa on 2013-06-11T08:50:55.000Z:

<b>What steps will reproduce the problem?</b>

The samples (ssExtra_ex01_AndroidRGBLamp and ssExtra_ex02_AndroidAirConditioner) does not proceed to the control screen when executed on typical screen landscape mode.

The test was performed on the devices: Sansung Galaxy tab 7 &quot;GT P3100 Galaxy S3 and mini.

**Comment by plinioseniore** [comment]
https://github.com/souliss/soulissapp/issues/18
