### ISSUE TITLE
XMLinterface not transmit all slots

### ISSUE THREAD

**Issue by fazioa** [souliss/souliss#110]
Original [issue 113](https://code.google.com/p/souliss/issues/detail?id=113) created by fazioa on 2015-03-03T08:21:25.000Z:

<b>What steps will reproduce the problem?</b>
1.Access the XML interface from browser.
2.By friariello If the request exceeds 20 slot data transmission is incorrect

**Comment by plinioseniore** [comment]
The XML is no longer maintained and is actually available only as legacy support.
