### ISSUE TITLE
add item 'delay' at the "scenary" in souliss app

### ISSUE THREAD

**Issue by fazioa** [souliss/souliss#112]
Original [issue 115](https://code.google.com/p/souliss/issues/detail?id=115) created by fazioa on 2015-03-05T22:42:28.000Z:

THE CREATION OF SCENARIOS, CAN ONLY PUT CONTROL &quot;commands&quot;,

sometimes, even WOULD HAVE THE POSSIBILITY OF EARNINGS OF ADDING &quot;delay&quot; of X sec / min between commands entered

**Comment by plinioseniore** [comment]
https://github.com/souliss/soulissapp/issues/10
