### ISSUE TITLE
how to choose between multiple installations

### ISSUE THREAD

**Issue by fazioa** [souliss/souliss#113]
Original [issue 116](https://code.google.com/p/souliss/issues/detail?id=116) created by fazioa on 2015-03-08T09:01:56.000Z:

I'm posing a problem

I have one at home, of souliss, in the office it will install another

how to choose the one or the other between the two souliss ??

for now I would be obliged to set a souliss with a local url different for the two locations, and cambaire the local address and dyndns used on soulissapp

in this way it finds the souliss on a local address, the look on the remote

But it is annoying and inelegant

have the ability to set various LOCATIONS (the term account does not seem right to me) would be better and then cycle between the two

thanks :-)

**Comment by juanpintom** [comment]
I think its possible if you work over OH,
