### ISSUE TITLE
tag on SoulissApp

### ISSUE THREAD

**Issue by fazioa** [souliss/souliss#114]
Original [issue 117](https://code.google.com/p/souliss/issues/detail?id=117) created by fazioa on 2015-03-11T07:30:33.000Z:

FOR SOULISSAPP 

1) La scheda TAG con la sola voce di default non è visibile in homepage

<b>What steps will reproduce the problem?</b>

...da App appena installata:
1. Rinomino TAG Preferiti in &quot;rientro casa&quot;
2. Inserisco secondo TAG
3. Provo a eliminare il TAG &quot;rientro casa&quot;, ricevo &quot;Can't remove default Favourite Tag&quot;
4. Provo ad eliminare il secondo TAG, ricevo &quot;Can't remove default Favourite Tag&quot;

<b>What is the expected output? What do you see instead?</b>
Mi aspetterei, pur avendo il TAG di default, di poterlo cancellare. 
In alternativa di poter cancellare quello di default e di poterne lasciare almeno uno in sua vece.
Al momento ho due TAG entrambi NON PIU' CANCELLABILI.

<b>What version of the app and framework are you using?</b>
1.5.1

**Comment by plinioseniore** [comment]
https://github.com/souliss/soulissapp/issues/9
