### ISSUE TITLE
T58 Bug On Android APP Reading T51 OK

### ISSUE THREAD

**Issue by fazioa** [souliss/souliss#115]
Original [issue 118](https://code.google.com/p/souliss/issues/detail?id=118) created by fazioa on 2015-03-12T03:29:53.000Z:

<b>What steps will reproduce the problem?</b>

With T51 I get the right value (1022.5) but when I change to T58 reads 756 hPA

<b>What is the expected output? What do you see instead?</b>

I think that problem is the (* 3) on line 61 of this file:
https://code.google.com/p/souliss/source/browse/SoulissApp/src/main/java/it/angelic/soulissclient/model/typicals/SoulissTypical58PressureSensor.java?repo=soulissapp

<b>Please use labels and text to provide additional information.</b>

**Comment by plinioseniore** [comment]
https://github.com/souliss/soulissapp/issues/7
