### ISSUE TITLE
Temperature control T31

### ISSUE THREAD

**Issue by fazioa** [souliss/souliss#12]
Original [issue 13](https://code.google.com/p/souliss/issues/detail?id=13) created by fazioa on 2013-06-11T20:21:36.000Z:

The temperature control T31 is not implemented in the Android interface,
is requested a faceplate with increase and decrease buttons, the T31 has two slot one for measured temperature and another for delta with requested setpoint.

The temperature is stored in values from 0x10 to 0x7F that correspond to maximum and minumum temperature values measured or scaled, at Android interface a scaling is requested to display the values in Celsius.

**Comment by juanpintom** [comment]
Any news from this?  Do you need some tests? I'll try tomorrow with a T31 on a node and let you know.

Regards

**Comment by fazioa** [comment]
I'm working. I need a lot of time.
Il 23/apr/2015 21:43, "juanpintom" notifications@github.com ha scritto:

**Comment by plinioseniore** [comment]
https://github.com/souliss/soulissapp/issues/17
