### ISSUE TITLE
T21 - T22 Bug on Commands Close and Toggle Commands

### ISSUE THREAD

**Issue by juanpintom** [souliss/souliss#136]
I found that CloseCmd_Local and Toggle are assigned to the same HEX, this cause on my tests I have incorrect behaviour, It sends Toggle instead Close :( Can you confirm if this is correct?

Here is the line:
https://github.com/souliss/souliss/blob/friariello/Typicals.h#L138

And the commands:
# define Souliss_T2n_CloseCmd_Local      0x08
# define Souliss_T2n_ToggleCmd       0x08

**Comment by ribico** [comment]
Ciao Juan,
I think it was my fault.
I always use toggle so I did not notice the bug.

It seems to me that 0xB0 is not used, would you please try with it ?

**Comment by plinioseniore** [comment]
Just changes as 0x12.
