### ISSUE TITLE
persistance crash

### ISSUE THREAD

**Issue by Autohome2** [souliss/souliss#138]
gateway code is working without persistance enabled but if enabled gateway hangs?
changing the slot/node values has no effect on this
Darren

**Comment by Autohome2** [comment]
i have just done a rollback to commit 7ad9cba  and no crash occurs ,xml server startup still wont compile though
Darren

**Comment by plinioseniore** [comment]
Please report your compile error if problem persist.

**Comment by plinioseniore** [comment]
As discussed here https://goo.gl/pSwGu8 the configuration file XMLinterface.h wasn't included as last configuration option in the list, that is why the sketch wasn't compiling
