### ISSUE TITLE
SOULISS_DEBUG give no Output

### ISSUE THREAD

**Issue by lesjaw** [souliss/souliss#159]
# define SOULISS_DEBUG_INSKETCH
# define SOULISS_DEBUG       1

There are no output at all when enabling souliss debug..

**Comment by plinioseniore** [comment]
Hi Les, could you please have a try again with the last available commit?

**Comment by lesjaw** [comment]
Oke will try again tonight..

**Comment by lesjaw** [comment]
Still No Output..

**Comment by lesjaw** [comment]
Want to update.. It works
