### ISSUE TITLE
Gateway.h from compile time to runtime

### ISSUE THREAD

**Issue by lesjaw** [souliss/souliss#160]
To make Souliss board compatible with ESP web config,  I need to change the gateway code changes from compile time to runtime.. specially this ;
# define MaCaco_USERMODE         1
# define MaCaco_SUBSCRIBERS          1

thanks

**Comment by plinioseniore** [comment]
Duplicated of #156, please look at #156 for more details on how get your node running as a Gateway at runtime and report your feedback.
