### ISSUE TITLE
WebConfig Add link to download SoulissApp

### ISSUE THREAD

**Issue by plinioseniore** [souliss/souliss#171]
A link to download SoulissApp once in the WebConfig HTML page is actually missing.

**Comment by juanpintom** [comment]
Ill add in a while.

Regards

**Comment by juanpintom** [comment]
Done but isn't tested

Regards

2015-09-08 14:35 GMT+02:00 Juan Pinto juanpintom@gmail.com:

> Ill add in a while.
> 
> Regards

**Comment by plinioseniore** [comment]
Thanks
