### ISSUE TITLE
call of overloaded 'Souliss_GetIPAddress()' is ambiguous

### ISSUE THREAD

**Issue by terrag42** [souliss/souliss#184]
Hello, cloned the latest Friariello Souliss library into my Arduino "libraries" folder and tried to compile a sketch, but I'm getting the following error: "call of overloaded 'Souliss_GetIPAddress()' is ambiguous". I was able to compile with no errors with the previous version.

**Comment by plinioseniore** [comment]
Hi, could you please share here the sketch that is giving you this error?

**Comment by terrag42** [comment]
[Here's the sketch](http://hastebin.com/elinawosoq.pl) I'm trying to compile for my ESP8266.

**Comment by plinioseniore** [comment]
Pull the latest commit and have fun :)
