### ISSUE TITLE
Analog values doesn't process zero value

### ISSUE THREAD

**Issue by plinioseniore** [souliss/souliss#188]
If zero value is passed, that isn't processed ad updated to SoulissApp and other nodes.

**Comment by plinioseniore** [comment]
@fazioa @mcbittech have you found the same problem while using the thermostat?

**Comment by juanpintom** [comment]
Yes, this value isn't processed, I always use an if (value = 0) value = 0.01;

Regards

**Comment by plinioseniore** [comment]
I've tested that the node now converts zero in 0x8000, so from the node side things looks ok. I need someone else to test, @juanpintom if you can have a try.

**Comment by plinioseniore** [comment]
@juanpintom had a try? I had a test just now and looks working fine, reopen the issue if you will have problems

**Comment by juanpintom** [comment]
Ok, if I found something wrong I let you know

Regards

2015-11-08 16:49 GMT+01:00 Dario Di Maio notifications@github.com:
