### ISSUE TITLE
Move the DEBUG #define in the configuration file

### ISSUE THREAD

**Issue by plinioseniore** [souliss/souliss#198]
Having the DEBUG #define configurable will give more freedom and support for debugging out of USART, as example we can print messages on a Telnet connection.

**Comment by juanpintom** [comment]
This will be awesome!, we can get debug of ESP nodes via wifi .)

Good idea!

Regards

2015-10-25 17:12 GMT+01:00 Dario Di Maio notifications@github.com:

**Comment by plinioseniore** [comment]
4bb31428518
