### ISSUE TITLE
T52 only -20???

### ISSUE THREAD

**Issue by brutevinch** [souliss/souliss#204]
Please tell me what if i want to measure -32C? maybe "add -40 capability" will be feature request?

**Comment by brutevinch** [comment]
Typical 52 : Temperature measure (-20, +50) °C ---- strange but -32.4C works well..... What seems (-20, +50) °C

**Comment by plinioseniore** [comment]
Hi, that is only the range of the bar on SoulissApp, but you can represent
any value.
