### ISSUE TITLE
Support for new 2.0 ESP8266 cores

### ISSUE THREAD

**Issue by plinioseniore** [souliss/souliss#214]
New ESP8266 cores has been relased in staging, support shall be extended. In the new cores:
1) A rewritten OTA support
2) PWM handled directly in RAM, this remove the needs for some tricky workarounds included in the LYT8266 examples.

**Comment by plinioseniore** [comment]
The branch esp8266_core2 has started

**Comment by juanpintom** [comment]
Im working with 2.0 and webupdate without problems.

PWM it's working well but I see blinks (bright changes) sometimes.

Regards

2016-01-04 12:05 GMT+01:00 Dario Di Maio notifications@github.com:

**Comment by dariocdj** [comment]
Juan also with 1.6 with my dimmer sometimes it blinks one time....

Inviato da smartphone Samsung Galaxy.

-------- Messaggio originale --------
Da: Juan Pinto notifications@github.com 
Data:04/01/2016  18:45  (GMT+01:00) 
A: souliss/souliss souliss@noreply.github.com 
Cc: Dario cdj@deskservice.com 
Oggetto: Re: [souliss] Support for new 2.0 ESP8266 cores (#214) 

Im working with 2.0 and webupdate without problems.

PWM it's working well but I see blinks (bright changes) sometimes.

Regards

2016-01-04 12:05 GMT+01:00 Dario Di Maio notifications@github.com:
