### ISSUE TITLE
Warning Error, redeclared Souliss_T1n_BrightDefault at Typicals.h

### ISSUE THREAD

**Issue by juanpintom** [souliss/souliss#222]
Isn't important, just a Warning on compilation, Souliss_T1n_BrightDefault  is defined here:
https://github.com/souliss/souliss/blob/friariello/Typicals.h#L103
And here again with a different value:
https://github.com/souliss/souliss/blob/friariello/Typicals.h#L109

Regards.

**Comment by plinioseniore** [comment]
Latest commit has a fix for this
