### ISSUE TITLE
 Pulse mode command to relay

### ISSUE THREAD

**Issue by DD-WRT** [souliss/souliss#237]
Hello everyone,
 I need a sketch for pulse mode command to relay, or if someone can explain how to change it in my sketch .

*how to change the output pin to operate in pulse mode ?
*how to change the input pin to see if it is active, it shows the current situation ??
(while having a trigger output to display ON when there is no input trigger to display OFF ) 

Thanks

**Comment by plinioseniore** [comment]
If you need that the state of the logics stays at ON and the output get pulsed, use PulseDigOut. Otherwise use T14 to get a pulsed state.

**Comment by DD-WRT** [comment]
Thanks for the quick response works perfectly with T14 .
