### ISSUE TITLE
Wiki Typicals revision

### ISSUE THREAD

**Issue by dariocdj** [souliss/souliss#245]
If you like you can add at the end of typical wiki page : 

Souliss SLOT are related only to single node. 
For example, You can have two T11 with SLOT 0 in the same souliss network, but you can't have two T11 with SLOT 0 in the same node.
Be careful that each typical - as you can see above - has assigned a number of slot. 

Example : T11 use only one slot, T16 use four slot and T19 two slot. So - BE CAREFUL IN THE SAME NODE - you can define node as : 
# define MyT19Node 0 //this typical use 2 slot so the next slot available is 2
# define MyT16Node 2 //this tipical use 4 slot so the next slot available is 6
# define MyT11Node 6 //this typical use 1 slot so the next slot available is 7.......

**# So you can have another node with the same typicals and with the same slots number, obviously with a different vnet address.**

**Comment by plinioseniore** [comment]
Done, https://github.com/souliss/souliss/wiki/Typicals
