### ISSUE TITLE
Unstable NRF24L01 network

### ISSUE THREAD

**Issue by artur3** [souliss/souliss#246]
Souliss app loses connection with NRF24L01 nodes.
Nodes need lot of time to obtain dynamic address from gateway.
One node stops working when other node is connected.

It looks that updating nRF24 driver in Souliss with code from current RF24 library solves most problems.
Updated driver code:
[RF24.zip](https://github.com/souliss/souliss/files/157430/RF24.zip)

**Comment by plinioseniore** [comment]
Thanks @artur3 I've merged that nRF24 code into a new branch, we need more people to test it and verify the functionality. Not all nRF24 radios behave as the same and many clones are out there.

https://github.com/souliss/souliss/tree/new_nRF24_AVR
