### ISSUE TITLE
fix crash on use ESP8266 WEBCONFinterface

### ISSUE THREAD

**Issue by ghost** [souliss/souliss#249]
interfaces/mcu_esp8266/webconfig/src/netconfig.h

```
- server.send ( 200, "text/html", PAGE_NetworkConfiguration );
+ server.send_P ( 200, "text/html", PAGE_NetworkConfiguration );
```

P.S. http://www.esp8266.com/viewtopic.php?f=8&t=4685

**Comment by plinioseniore** [comment]
@setar could you please make a pull request with the modified file?

Thanks.

**Comment by plinioseniore** [comment]
@jkutianski could you please have a check and pull the modified files into 720_rc?

Thanks,
Dario.

**Comment by jkutianski** [comment]
Dario.

I'm working on it
Best.

Juan Pablo

**Comment by jkutianski** [comment]
@setar could you please test it?

**Comment by jkutianski** [comment]
I will close the issue. If the problem persist, please reopen it.
