### ISSUE TITLE
Value from Typical T58 (pressure sensor) is not updated

### ISSUE THREAD

**Issue by artur3** [souliss/souliss#252]
Value from Typical T58 (pressure sensor) is not updated (constant pressure is shown) in soulissApp and openHaB. Resetting board usually solves the problem for short time.
Value printed to serial port is correct and changes over the time.
Other sensors are working fine.

Code (Arduino Mega + eth shield):
Setup
`// Set the typical to use
  Set_T52(TEMP1);
  Set_T53(HUMIDITY);
  Set_T54(LIGHT);
  Set_T58(PRESSURE);
  Set_T52(TEMP2);`

Loop
   ` FAST_11110ms()
    {
      float temp1 = dht.readTemperature();
      ImportAnalog(TEMP1, &temp1);

```
  float humidity = dht.readHumidity();
  ImportAnalog(HUMIDITY, &humidity);

  float temp2 = bmp.readTemperature();
  ImportAnalog(TEMP2, &temp2);

  float pressure = bmp.readPressure();
  pressure = pressure / 100;
  ImportAnalog(PRESSURE, &pressure);

  float lux = lightMeter.readLightLevel();
  ImportAnalog(LIGHT, &lux);
```
# if defined(_DEBUG_)

```
  Serial.println();
  Serial.print ("Temp 1 = ");
  Serial.print (temp1);
  Serial.println(" *C");
  Serial.print ("Hum = ");
  Serial.print (humidity);
  Serial.println(" %");
  Serial.print("Temp 2 = ");
  Serial.print(temp2);
  Serial.println(" *C");
  Serial.print("Pressure = ");
  Serial.print(pressure);
  Serial.println(" hPa");
  Serial.print("Light = ");
  Serial.print(lux);
  Serial.println(" lx");
  Serial.println();
```
# endif

```
  // Compare the acquired input with the stored one, send the new value to the
  // user interface if the difference is greater than the deadband

  Logic_T52(TEMP1);
  Logic_T52(TEMP2);
  Logic_T53(HUMIDITY);
  Logic_T54(LIGHT);
  Logic_T58(PRESSURE);

  // Retreive data from the MaCaco communication channel
  ProcessCommunication();
}
```

`

**Comment by plinioseniore** [comment]
Data are transferred with a deadband, so if you are below that deadband nothing is transferred. Actually is 1.5% of last visualized value.
https://github.com/souliss/souliss/blob/friariello/base/SpeakEasy.h#L211

**Comment by artur3** [comment]
You're right, 0,015 from thousands is more than usually pressure changes.
Maybe default deadband for pressure should be lowered?

**Comment by plinioseniore** [comment]
What's the resolution of your sensor compared to the full range? Better that 1.5%?

**Comment by artur3** [comment]
For example, serial port shows today 992 but SoulissApp still shows 998 from yesterday. Charts for pressure are flat line for days.  998 \* 0.015 = 14,97

**Comment by artur3** [comment]
BMP180
Up to 0.03hPa / 0.25m resolution
-40 to +85°C operational range, +-2°C temperature accuracy

I use Adafruit_BMP085 lib.

**Comment by plinioseniore** [comment]
Lower your value to 0.0015 and let me know if you network slows down due to an excess of data notified.

**Comment by artur3** [comment]
Is the amount of data does not depend on how often I read sensors? Even every few minutes or less should be enough. 
Problem is 1.5% from thousands, that's more than usually pressure changes, so far my readings shows about 994 to 1015hPa.

**Comment by plinioseniore** [comment]
Yep, you can slow down you measure read to be sure that it will not send data too much data. Consider that a node works reliably at an average of 1 update/s rate.

This is conservative value and the real one depends on your network structure and nodes.
