### ISSUE TITLE
Typical T16 is not reporting data change 

### ISSUE THREAD

**Issue by artur3** [souliss/souliss#253]
`if (Logic_T11(LIGHT))
  {
...
}`  
works when data is changed. Same code for T16 is not working.

**Comment by plinioseniore** [comment]
That's strange, the T16 is supposed to transfer if a data has changes in case of ON/OFF and not in case of change in bright or color.

**Comment by artur3** [comment]
Yesterday I found that this work for On/Off. But would be great to have this also for color and bright. So the command for the lamp can be send only when needed.

**Comment by plinioseniore** [comment]
The main problem is that this will create trouble when synchronizing with music. You can any how change your own code to get this adding the i_trigger code for the ifs that you need.

Let me know.

**Comment by artur3** [comment]
Ok. I can live with that.
Only the term "data change" is a bit misleading.
