### ISSUE TITLE
small smart home Help Wanted 

### ISSUE THREAD

**Issue by yasserhabh** [souliss/souliss#259]
Hello every one. i am Yasir student from Iraq . i have small project to make simple smart home system using Arduino and IoT . and i see souliss is very good platform for make it. but my problem i am not good in programming and i dont understand how i put T8,T16 and so on . if any one can help me in my situation. and if any one can discuss to me to understand how i program it
i have 
Arduino Mega2560 + ethernet W5100
8 chaneel relay board
2 Pir motion sensor 1 for auto light. 1 for alarm
2 photoresistor 1 for auto light 
buzzer for alarm
leds multi colors 
big thanks for anyone can help me or not. 
accept my best regards
Yasir Habh
yassermunther2003@gmail.com

**Comment by jkutianski** [comment]
Yasser.
All the T are called Typicals. You can found some help about typicals [here](https://github.com/souliss/souliss/wiki/Typicals)
T8 doesn't exist and T16 is RGB LED Strip.

For relay board you've to use Typical 11 : ON/OFF Digital Output with Timer Option, Typical 12 : ON/OFF Digital Output with AUTO mode or Typical 18 : ON/OFF Digital Output (Step Relay).

If you want to use Auto ON/OFF with PIR or photoresistor you've to use the T12.

For alarm you've to use T41.
