### ISSUE TITLE
LowDigInToState

### ISSUE THREAD

**Issue by Melkor82** [souliss/souliss#265]
Ho aggiunto la riga
 `#define   LowDigIn2State(pin,value_state_on,value_state_off,slot) Souliss_LowDigIn2State(pin, value_state_on, value_state_off, memory_map, slot)`
Nel file SpeakEasy.h Nel file base era previsto ma senza questa riga il codice non funzionava.

**Comment by plinioseniore** [comment]
La lingua ufficiale qui è l'inglese, in ogni caso ho fatto merge della tua pull request.
