### ISSUE TITLE
Dynamic IP adress problem

### ISSUE THREAD

**Issue by DD-WRT** [souliss/souliss#271]
This is my internet operator announced soon that my public address will be replaced with dynamic (meaning to change) 
Now the question is can I use the app souliss on dynamic IP addresses and how to adjust it.

Thank you

**Comment by plinioseniore** [comment]
You have to use a DDNS like no-ip.org or others, this will give you an hostname like yourhostname.no-ip.org that you should use instead of the public IP address in SoulissApp.
