### ISSUE TITLE
Add DigInHold2 and LowDigInHold2 

### ISSUE THREAD

**Issue by sdurnev** [souliss/souliss#325]
Hey! 
I suggest adding the following features.

### DigInHold2

Similar to DigInHold, but controls two different slots.

Single press ->  value_state1 -> slot1

Long press ->  value_state2 -> slot2

```C
U8 DigInHold2(U8 pin, U8 value_state1, U8 value_state2, U8 slot1, U8 slot2);
```

All details here -> https://github.com/sdurnev/souliss_svdu/commit/f0b07fbd6dac884653bc949a78c0b63c04174e7e

**Comment by plinioseniore** [comment]
Hi, can you please submit a pull request?

**Comment by sdurnev** [comment]
Can't create a new pull request: Push failed: remote: Permission to souliss/souliss.git denied to sdurnev. unable to access 'https://github.com/souliss/souliss.git/': The requested URL returned error: 403

Maybe I'm doing something wrong?

**Comment by sdurnev** [comment]
Thanks!

**Comment by plinioseniore** [comment]
I see you make two direct commits, one adding your code and one deleting

https://github.com/souliss/souliss/commit/f0b07fbd6dac884653bc949a78c0b63c04174e7e

https://github.com/souliss/souliss/commit/fe3b239c045bf4f254a397eac0066830691e4e5f

Please, go via pull request for next changes.

**Comment by sdurnev** [comment]
You're right.
I don't have much experience unfortunately.
This time my code is added.
I will consider your recommendations in the future.
Thanks!
