### ISSUE TITLE
T41  GUI problem when you reset allarm

### ISSUE THREAD

**Issue by fazioa** [souliss/souliss#38]
Original [issue 41](https://code.google.com/p/souliss/issues/detail?id=41) created by fazioa on 2013-10-10T14:44:09.000Z:

<b>What steps will reproduce the problem?</b>
1.T41 go in Allarm
2.Reset Allarm

<b>What is the expected output? What do you see instead?</b>
See the picture

<b>What version of the app and framework are you using?</b>
4.5.1 app 1.2.5

<b>Please provide any additional information below.</b>
See the picture

**Comment by plinioseniore** [comment]
https://github.com/souliss/soulissapp/issues/16
