### ISSUE TITLE
Enhanced IfThenElse Engine

### ISSUE THREAD

**Issue by fazioa** [souliss/souliss#54]
Original [issue 57](https://code.google.com/p/souliss/issues/detail?id=57) created by fazioa on 2014-03-26T07:32:38.000Z:

Actually the Engine that runs the scenario is only triggered by the timer for Service Execution. Please trig it also every time that data has been received from the gateway node.

The exponential backoff shall be modified to poll the GPS at rates that are indipendent from the timer of background Service.
Once near the position, the GPS can be polled frequently until we got inside the area. Then polls reduce their frequency.

For all triggers shall be inculed an AND + NOT condition with two gates and an execution maximum rate.
So a scenario maybe:
Do somenthis if I'm backhome AND (NOT) state from the &quot;typicals&quot; AND (NOT) state from &quot;typicals&quot;.
Execute this scenario no more than ONCE every (10 min) (30 min) (1 h) (1 day).

**Comment by plinioseniore** [comment]
https://github.com/souliss/soulissapp/issues/15
