### ISSUE TITLE
Node ids should be persistent and not change once joined

### ISSUE THREAD

**Issue by fazioa** [souliss/souliss#76]
Original [issue 79](https://code.google.com/p/souliss/issues/detail?id=79) created by fazioa on 2014-08-21T20:13:35.000Z:

It would be of interest to all to have a unique way of identifiying the nodes, not just when using the dynamic addressing. So at least there should be a way to interface with the gateway via a unique and static id. This could be both the network address and/or a UUID. 
If you are building your own nodes then a simple insketch option for UUID like the MAC address. 
Then when building the db in Souliss App, the UUID is included and can be used to identify the node until explicit deletion is requested. 
This would also make the openHAB integration usefull. 

My recommandation is to implement the UUID in the nodes, and store a table in the gateway.

**Comment by plinioseniore** [comment]
Starting from Souliss v7.0.3 the addresses obtained via dynamic addressing are stored in the EEPROM
