### ISSUE TITLE
SetIPAddress doesn't assign a proper vNet Supernode

### ISSUE THREAD

**Issue by fazioa** [souliss/souliss#80]
Original [issue 83](https://code.google.com/p/souliss/issues/detail?id=83) created by fazioa on 2014-08-26T08:50:27.000Z:

More information at this link
https://code.google.com/p/souliss/source/detail?r=1d45d9eee1be81e85fda00e769fa60eeb768f268

**Comment by plinioseniore** [comment]
Using SetIPAddress() there is no SuperNode set on the vNet stack, this result in problem when data have to be routed.

**Comment by plinioseniore** [comment]
This cannot be solved, if routing is required the SetAddress shall be used instead.
