### ISSUE TITLE
XML interface does not allways close socket.

### ISSUE THREAD

**Issue by fazioa** [souliss/souliss#87]
Original [issue 90](https://code.google.com/p/souliss/issues/detail?id=90) created by fazioa on 2014-10-17T18:20:38.000Z:

<b>What steps will reproduce the problem?</b>

1.Access the XML interface from browser
2.Sometimes the request does not get a reply and the socket is not closed.
This causes the browser to time out, but if you have a program that does not time out, the connection hangs forever.

**Comment by plinioseniore** [comment]
The XML interface is no longer maintained, is available only as legacy support.
