### ISSUE TITLE
Souliss app Typical 19 bugs

### ISSUE THREAD

**Issue by fazioa** [souliss/souliss#98]
Original [issue 101](https://code.google.com/p/souliss/issues/detail?id=101) created by fazioa on 2015-01-01T10:20:24.000Z:

<b>What steps will reproduce the problem?</b>
1.power commands  on last screen (screen where you can set the brightness) of the typical
2.It should be nice that in the scenes, you also could set the brighness. Now you can define ON, OFF &amp; toggle for this typical
<b>3.</b>

<b>What is the expected output? What do you see instead?</b>
when you give a OFF command, the light is not going out, but the brightness is going down with one step.
When you give a power On command, the slider stays on position zero sometimes.
It seems that the power ON &amp; OFF buttons on the last tab, are doing nearly the same as the brightness up &amp; down.

<b>What version of the app and framework are you using?</b>
1.3.1

Please provide any additional information below, and use Label &quot;App&quot; if you
<b>believe this is an App problem.</b>

**Comment by plinioseniore** [comment]
https://github.com/souliss/soulissapp/issues/13
